version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 300958834981.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Pulling the Docker image php:latest from private Amazon ECR
      - docker pull php:8.3-apache
      - echo Building the Docker image...          
      - docker build -t wordpress .
      - docker tag wordpress:latest 300958834981.dkr.ecr.us-east-1.amazonaws.com/wordpress:latest   
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 300958834981.dkr.ecr.us-east-1.amazonaws.com/php
